name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - name: Get cache directories
        id: cache_dirs
        run: |
          echo "::set-output name=yarn::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.cache_dirs.outputs.yarn }}
          key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ github.job }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build site
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build
          cname: dmxchancalc.dankeenan.org
